# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('warden_name', models.CharField(max_length=150)),
                ('senior_warden', models.CharField(max_length=150)),
                ('disciplinary_called', models.CharField(max_length=150)),
                ('complainant', models.CharField(max_length=150)),
                ('accomplices', models.CharField(max_length=150)),
                ('witnesses', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.CharField(max_length=12)),
                ('surname', models.CharField(max_length=60)),
                ('forename', models.CharField(max_length=60)),
                ('site', models.CharField(max_length=30)),
                ('hall', models.CharField(max_length=30)),
                ('room_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='IncidentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='wardens.IncidentType'),
        ),
        migrations.AddField(
            model_name='incident',
            name='halls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='wardens.Hall'),
        ),
        migrations.AddField(
            model_name='incident',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='wardens.Site'),
        ),
        migrations.AddField(
            model_name='incident',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='wardens.Student'),
        ),
        migrations.AddField(
            model_name='hall',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='wardens.Site'),
        ),
    ]
